// This file is auto-generated by @hey-api/openapi-ts

export type CreateEquipmentGroupDto = {
    /**
     * Tên của nhóm loại trang bị
     */
    name: string;
    /**
     * Mã định danh duy nhất cho nhóm
     */
    code: string;
    notes?: string;
};

export type CreateQualityLevelDto = {
    /**
     * Tên của phân cấp chất lượng
     */
    name: string;
    /**
     * Mã định danh duy nhất cho phân cấp
     */
    code: string;
    notes?: string;
};

export type CreateUnitDto = {
    /**
     * Tên đầy đủ của đơn vị
     */
    name: string;
    /**
     * Mã định danh duy nhất cho đơn vị
     */
    code: string;
    /**
     * ID của đơn vị cha (nếu có)
     */
    parentId?: string;
    description?: string;
};

export type CreateUserDto = {
    /**
     * Tên đăng nhập
     */
    username: string;
    /**
     * Mật khẩu
     */
    password: string;
    fullName?: string;
    role?: 'admin' | 'manager' | 'user';
};

export type role = 'admin' | 'manager' | 'user';

export type EquipmentGroupResponseDto = {
    _id: string;
    name: string;
    code: string;
    notes?: string;
    createdAt: string;
    updatedAt: string;
};

export type LoginDto = {
    username: string;
    password: string;
};

export type LoginResponseDto = {
    /**
     * JSON Web Token (JWT) để xác thực
     */
    access_token: string;
};

export type QualityLevelResponseDto = {
    _id: string;
    name: string;
    code: string;
    notes?: string;
    createdAt: string;
    updatedAt: string;
};

export type UnitResponseDto = {
    _id: string;
    name: string;
    code: string;
    parentId?: string;
    description?: string;
    createdAt: string;
    updatedAt: string;
};

export type UpdateEquipmentGroupDto = {
    /**
     * Tên của nhóm loại trang bị
     */
    name?: string;
    /**
     * Mã định danh duy nhất cho nhóm
     */
    code?: string;
    notes?: string;
};

export type UpdateQualityLevelDto = {
    /**
     * Tên của phân cấp chất lượng
     */
    name?: string;
    /**
     * Mã định danh duy nhất cho phân cấp
     */
    code?: string;
    notes?: string;
};

export type UpdateUnitDto = {
    /**
     * Tên đầy đủ của đơn vị
     */
    name?: string;
    /**
     * Mã định danh duy nhất cho đơn vị
     */
    code?: string;
    /**
     * ID của đơn vị cha (nếu có)
     */
    parentId?: string;
    description?: string;
};

export type UpdateUserDto = {
    fullName?: string;
    password?: string;
    username?: string;
    /**
     * Chỉ Admin mới có thể thay đổi
     */
    role?: 'admin' | 'manager' | 'user';
};

export type UserResponseDto = {
    /**
     * ID của người dùng
     */
    _id: string;
    username: string;
    fullName: string;
    role: 'admin' | 'manager' | 'user';
    createdAt: string;
    updatedAt: string;
};

export type AuthControllerSignInData = {
    body: LoginDto;
};

export type AuthControllerSignInResponse = (LoginResponseDto);

export type AuthControllerSignInError = (unknown);

export type EquipmentGroupsControllerCreateData = {
    body: CreateEquipmentGroupDto;
};

export type EquipmentGroupsControllerCreateResponse = (EquipmentGroupResponseDto);

export type EquipmentGroupsControllerCreateError = (unknown);

export type EquipmentGroupsControllerFindAllResponse = (Array<EquipmentGroupResponseDto>);

export type EquipmentGroupsControllerFindAllError = unknown;

export type EquipmentGroupsControllerFindOneData = {
    path: {
        /**
         * ID của nhóm
         */
        id: string;
    };
};

export type EquipmentGroupsControllerFindOneResponse = (EquipmentGroupResponseDto);

export type EquipmentGroupsControllerFindOneError = (unknown);

export type EquipmentGroupsControllerUpdateData = {
    body: UpdateEquipmentGroupDto;
    path: {
        /**
         * ID của nhóm
         */
        id: string;
    };
};

export type EquipmentGroupsControllerUpdateResponse = (EquipmentGroupResponseDto);

export type EquipmentGroupsControllerUpdateError = (unknown);

export type EquipmentGroupsControllerRemoveData = {
    path: {
        /**
         * ID của nhóm
         */
        id: string;
    };
};

export type EquipmentGroupsControllerRemoveResponse = (void);

export type EquipmentGroupsControllerRemoveError = (unknown);

export type QualityLevelsControllerCreateData = {
    body: CreateQualityLevelDto;
};

export type QualityLevelsControllerCreateResponse = (QualityLevelResponseDto);

export type QualityLevelsControllerCreateError = (unknown);

export type QualityLevelsControllerFindAllResponse = (Array<QualityLevelResponseDto>);

export type QualityLevelsControllerFindAllError = unknown;

export type QualityLevelsControllerFindOneData = {
    path: {
        /**
         * ID của phân cấp
         */
        id: string;
    };
};

export type QualityLevelsControllerFindOneResponse = (QualityLevelResponseDto);

export type QualityLevelsControllerFindOneError = (unknown);

export type QualityLevelsControllerUpdateData = {
    body: UpdateQualityLevelDto;
    path: {
        /**
         * ID của phân cấp
         */
        id: string;
    };
};

export type QualityLevelsControllerUpdateResponse = (QualityLevelResponseDto);

export type QualityLevelsControllerUpdateError = (unknown);

export type QualityLevelsControllerRemoveData = {
    path: {
        /**
         * ID của phân cấp
         */
        id: string;
    };
};

export type QualityLevelsControllerRemoveResponse = (void);

export type QualityLevelsControllerRemoveError = (unknown);

export type UnitsControllerCreateData = {
    body: CreateUnitDto;
};

export type UnitsControllerCreateResponse = (UnitResponseDto);

export type UnitsControllerCreateError = (unknown);

export type UnitsControllerFindAllResponse = (Array<UnitResponseDto>);

export type UnitsControllerFindAllError = unknown;

export type UnitsControllerFindOneData = {
    path: {
        /**
         * ID của đơn vị
         */
        id: string;
    };
};

export type UnitsControllerFindOneResponse = (UnitResponseDto);

export type UnitsControllerFindOneError = (unknown);

export type UnitsControllerUpdateData = {
    body: UpdateUnitDto;
    path: {
        /**
         * ID của đơn vị
         */
        id: string;
    };
};

export type UnitsControllerUpdateResponse = (UnitResponseDto);

export type UnitsControllerUpdateError = (unknown);

export type UnitsControllerRemoveData = {
    path: {
        /**
         * ID của đơn vị
         */
        id: string;
    };
};

export type UnitsControllerRemoveResponse = (void);

export type UnitsControllerRemoveError = (unknown);

export type UsersControllerCreateData = {
    body: CreateUserDto;
};

export type UsersControllerCreateResponse = (UserResponseDto);

export type UsersControllerCreateError = (unknown);

export type UsersControllerFindAllResponse = (Array<UserResponseDto>);

export type UsersControllerFindAllError = unknown;

export type UsersControllerFindOneData = {
    path: {
        /**
         * ID của người dùng
         */
        id: string;
    };
};

export type UsersControllerFindOneResponse = (UserResponseDto);

export type UsersControllerFindOneError = (unknown);

export type UsersControllerUpdateData = {
    body: UpdateUserDto;
    path: {
        /**
         * ID của người dùng cần sửa
         */
        id: string;
    };
};

export type UsersControllerUpdateResponse = (UserResponseDto);

export type UsersControllerUpdateError = (unknown);

export type UsersControllerRemoveData = {
    path: {
        /**
         * ID của người dùng cần xoá
         */
        id: string;
    };
};

export type UsersControllerRemoveResponse = (void);

export type UsersControllerRemoveError = (unknown);