// This file is auto-generated by @hey-api/openapi-ts

export type CreateUserDto = {
    /**
     * Tên đăng nhập
     */
    username: string;
    /**
     * Mật khẩu
     */
    password: string;
    fullName?: string;
    role?: 'admin' | 'manager' | 'user';
};

export type role = 'admin' | 'manager' | 'user';

export type LoginDto = {
    username: string;
    password: string;
};

export type LoginResponseDto = {
    /**
     * JSON Web Token (JWT) để xác thực
     */
    access_token: string;
};

export type UpdateUserDto = {
    fullName?: string;
    password?: string;
    username?: string;
    /**
     * Chỉ Admin mới có thể thay đổi
     */
    role?: 'admin' | 'manager' | 'user';
};

export type UserResponseDto = {
    /**
     * ID của người dùng
     */
    _id: string;
    username: string;
    fullName: string;
    role: 'admin' | 'manager' | 'user';
    createdAt: string;
    updatedAt: string;
};

export type AuthControllerSignInData = {
    body: LoginDto;
};

export type AuthControllerSignInResponse = (LoginResponseDto);

export type AuthControllerSignInError = (unknown);

export type UsersControllerCreateData = {
    body: CreateUserDto;
};

export type UsersControllerCreateResponse = (UserResponseDto);

export type UsersControllerCreateError = (unknown);

export type UsersControllerFindAllResponse = (Array<UserResponseDto>);

export type UsersControllerFindAllError = unknown;

export type UsersControllerFindOneData = {
    path: {
        /**
         * ID của người dùng
         */
        id: string;
    };
};

export type UsersControllerFindOneResponse = (UserResponseDto);

export type UsersControllerFindOneError = (unknown);

export type UsersControllerUpdateData = {
    body: UpdateUserDto;
    path: {
        /**
         * ID của người dùng cần sửa
         */
        id: string;
    };
};

export type UsersControllerUpdateResponse = (UserResponseDto);

export type UsersControllerUpdateError = (unknown);

export type UsersControllerRemoveData = {
    path: {
        /**
         * ID của người dùng cần xoá
         */
        id: string;
    };
};

export type UsersControllerRemoveResponse = (void);

export type UsersControllerRemoveError = (unknown);